export const paymentsAR = [
  // --- BILLETERAS Y DIGITALES ---
  { id: 'astropay', name: 'AstroPay', type: 'wallet', appUrl: null, fallbackUrl: 'https://astropay.com' },
  { id: 'brubank', name: 'Brubank', type: 'digital_bank', appUrl: 'brubank://', fallbackUrl: 'https://www.brubank.com' },
  { id: 'cencopay', name: 'CencoPay', type: 'wallet', appUrl: null, fallbackUrl: 'https://www.cencopay.com.ar' },
  { id: 'claropay', name: 'Claro Pay', type: 'wallet', appUrl: null, fallbackUrl: 'https://www.claropay.com.ar' },
  { id: 'cocos', name: 'Cocos', type: 'wallet', appUrl: null, fallbackUrl: 'https://cocos.capital' },
  { id: 'cuentadni', name: 'Cuenta DNI', type: 'wallet', appUrl: null, fallbackUrl: 'https://www.bancoprovincia.com.ar/cuentadni' },
  { id: 'dolarapp', name: 'Dolar App', type: 'wallet', appUrl: null, fallbackUrl: 'https://www.dolarapp.com' },
  { id: 'lemon', name: 'Lemon', type: 'wallet', appUrl: 'lemoncash://', fallbackUrl: 'https://www.lemon.me' },
  { id: 'mercadopago', name: 'Mercado Pago', type: 'wallet', appUrl: 'mercadopago://', fallbackUrl: 'https://www.mercadopago.com.ar' },
  { id: 'modo', name: 'MODO', type: 'aggregator', appUrl: 'modo://', fallbackUrl: 'https://www.modo.com.ar' },
  { id: 'naranjax', name: 'Naranja X', type: 'wallet', appUrl: 'naranjax://', fallbackUrl: 'https://www.naranjax.com' },
  { id: 'personalpay', name: 'Personal Pay', type: 'wallet', appUrl: 'personalpay://', fallbackUrl: 'https://www.personalpay.com.ar' },
  { id: 'prex', name: 'Prex', type: 'wallet', appUrl: 'prex://', fallbackUrl: 'https://www.prexcard.com.ar' },
  { id: 'ripio', name: 'Ripio', type: 'wallet', appUrl: null, fallbackUrl: 'https://www.ripio.com' },
  { id: 'uala', name: 'Ualá', type: 'wallet', appUrl: 'uala://', fallbackUrl: 'https://www.uala.com.ar' },
  { id: 'yoy', name: 'YOY', type: 'digital_bank', appUrl: null, fallbackUrl: 'https://www.yoy.com.ar' },

  // --- BANCOS TRADICIONALES Y TARJETAS ---
  { id: 'bbva', name: 'Banco BBVA', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bbva.com.ar' },
  { id: 'bpn', name: 'BPN', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bpn.com.ar' },
  { id: 'cabal', name: 'Cabal', type: 'card', appUrl: null, fallbackUrl: 'https://www.cabal.coop' },
  { id: 'ciudad', name: 'Banco Ciudad', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancociudad.com.ar' },
  { id: 'columbia', name: 'Banco Columbia', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancocolumbia.com.ar' },
  { id: 'comafi', name: 'Banco Comafi', type: 'bank', appUrl: null, fallbackUrl: 'https://www.comafi.com.ar' },
  { id: 'credicoop', name: 'Banco Credicoop', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancocredicoop.coop' },
  { id: 'galicia', name: 'Banco Galicia', type: 'bank', appUrl: null, fallbackUrl: 'https://www.galicia.ar' },
  { id: 'hipotecario', name: 'Banco Hipotecario', type: 'bank', appUrl: null, fallbackUrl: 'https://www.hipotecario.com.ar' },
  { id: 'hsbc', name: 'Banco HSBC', type: 'bank', appUrl: null, fallbackUrl: 'https://www.hsbc.com.ar' },
  { id: 'icbc', name: 'ICBC', type: 'bank', appUrl: null, fallbackUrl: 'https://www.icbc.com.ar' },
  { id: 'itau', name: 'Banco Itaú', type: 'bank', appUrl: null, fallbackUrl: 'https://www.itau.com.ar' },
  { id: 'macro', name: 'Banco Macro', type: 'bank', appUrl: null, fallbackUrl: 'https://www.macro.com.ar' },
  { id: 'nacion', name: 'Banco Nación', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bna.com.ar' },
  { id: 'patagonia', name: 'Banco Patagonia', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancopatagonia.com.ar' },
  { id: 'piano', name: 'Banco Piano', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancopiano.com.ar' },
  { id: 'provincia', name: 'Banco Provincia', type: 'bank', appUrl: null, fallbackUrl: 'https://www.bancoprovincia.com.ar' },
  { id: 'santander', name: 'Banco Santander', type: 'bank', appUrl: null, fallbackUrl: 'https://www.santander.com.ar' },
  { id: 'supervielle', name: 'Banco Supervielle', type: 'bank', appUrl: null, fallbackUrl: 'https://www.supervielle.com.ar' }
];